### ISSUE TITLE
Triqs: MeshProduct

### ISSUE THREAD

**Issue by fsxbhyy** [numericalEFT/GreenFunc.jl#32]
-Complete the TODO list for basic functions in MeshProduct, including:

- [x] 1.new functions:
 All listed Basic functions  which enables the use of julia iterator

- [x] 2. Assertion and edge cases:
 Add assertions to make sure the user input is eligible for functions

- [x] 3. Unit test
 Add test in test_MeshProduct.jl.

**Comment by kunyuan** [comment]
Should be done
